### ISSUE TITLE
Request new service account to run az cli and tf commands

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/dibbs-cloud#7]
### Background
To permit automation, we need a service account that has permissions to run commands against our Azure environment.

### Action requested
- File a ticket with the CDC AD Helpdesk to create a service account.
- The account should have the same Contributor Light permissions that we use as developers.

### Acceptance Criteria
- Service account exists
- Account has Contributor Light permissions
- Credentials for account are properly added to GitHub for usage in workflows.

### Additional context
None.

**Comment by boris-ning-usds** [comment]
Ah Service Principal / App Registration is what you want instead of Service Accounts.
Service Principal / App Registrations are managed identity within Azure Entra / Azure Active Directory (AAD) for automation of Azure Cloud infrastructure.

Service Accounts are allocated by on-premise Active Directory / Domain Controllers and are used as managed identity for Office365.

**Comment by boris-ning-usds** [comment]
Also, you can also do OpenID Connect as the owner of the Service Principal / App Registration so that you can federate Github <-> Azure Cloud without having to store your client secret in Github. This means less client secrets to deal with, and not having to worry about expiration as long the federation exist.

The Github action will generate a one time JWT token on azure/login and last for an hour upon OpenID federation.
